package com.cg.hims.entities;

import java.io.Serializable;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
/**
 * 
 * @author  Rahul
 * Pojo class of policy.policyId is autogenerated.
 *
 */
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@Table(name="Policy")
public class Policy implements Serializable {
    
	public Policy(String policyName, LocalDate policyEndDate, LocalDate policyEffectiveDate, int policyTerm,
			String policyStatus) {
		super();
		this.policyName = policyName;
		this.policyEndDate = policyEndDate;
		this.policyEffectiveDate = policyEffectiveDate;
		this.policyTerm = policyTerm;
		this.policyStatus = policyStatus;
	}
	@Id
    @Column(name="policy_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
	private int policyId;
    @Column(name="policy_name")
	private String policyName;
    @Column(name="policy_end_date")
	private LocalDate policyEndDate;
    @Column(name="policy_effective_date")
	private LocalDate policyEffectiveDate;
    @Column(name="policy_term")
	private int policyTerm;
    @Column(name="policy_status")
	private String policyStatus;
//	@OneToMany(mappedBy="Policy")
//	private List<Transactions> TransactionsList;
//	private PolicyHolder policyHolder;
//	@ManyToOne(cascade = CascadeType.ALL)
//	@JsonIgnore
//	private Admin admin;

}
